In [1]:
import pandas as pd
import sklearn
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
Results_L = cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target, cv=6)
Results_L

array([0.91666667, 0.92666667, 0.92666667, 0.95986622, 0.93311037,
       0.90635452])

In [5]:
Results_RF = cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=6)
Results_RF

array([0.94      , 0.97      , 0.95333333, 0.96655518, 0.97993311,
       0.909699  ])

In [6]:
Results_SVC = cross_val_score(SVC(), digits.data, digits.target, cv=6)
Results_SVC

array([0.96333333, 0.96666667, 0.98666667, 0.97993311, 0.99331104,
       0.92976589])

In [7]:
import numpy as np

In [8]:
Average_Score_L = np.mean(Results_L)
Average_Score_RF = np.mean(Results_RF)
Average_Score_SVC  = np.mean(Results_SVC)

In [9]:
print(Average_Score_L,Average_Score_RF, Average_Score_SVC)

0.9282218506131549 0.9532534373838722 0.9699461166852471
