In [1]:
import pandas as pd
import sklearn
from sklearn.datasets import load_iris
Flowers= load_iris()


In [2]:
dir(Flowers)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [11]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [15]:
Results_L = cross_val_score(LogisticRegression(max_iter=1000), Flowers.data, Flowers.target, cv=6)
Results_L

array([0.96, 1.  , 0.96, 0.92, 0.96, 1.  ])

In [16]:
Results_RF = cross_val_score(RandomForestClassifier(), Flowers.data, Flowers.target, cv=6)
Results_RF

array([0.96, 1.  , 0.92, 0.92, 0.92, 1.  ])

In [17]:
Results_SVC = cross_val_score(SVC(), Flowers.data, Flowers.target, cv=6)
Results_SVC 

array([0.96, 1.  , 1.  , 0.92, 1.  , 1.  ])

In [18]:
import numpy as np

In [19]:
Average_Score_L = np.mean(Results_L)
Average_Score_RF = np.mean(Results_RF)
Average_Score_SVC  = np.mean(Results_SVC)

In [ ]:
print(Average_Score_L, Average_Score_RF ,Average_Score_SVC 